name: Build Pull Request
on: push

jobs:
  test_job:
    name: AssembleDebugAPK
    runs-on: ubuntu-latest
    steps:
      - name: Check out code of current branch
        uses : actions/checkout@v2

      - name: Speed-up by Restoring Gradle Cache from Previous Builds
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*')}}
          restore-keys: |
            ${{runner.os}}-gradle-

      - name: Assesmble Debug Apk
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk