name: Build Pull Request
on: push

jobs:
  assemble_debug_job:
    name: AssembleDebugAPK
    runs-on: ubuntu-latest
    steps:
      - name: Check out code of current branch
        uses: actions/checkout@v2

      - name: Speed-up by Restoring Gradle Cache from Previous Builds
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*')}}
          restore-keys: |
            ${{runner.os}}-gradle-

      - name: Assesmble Debug Apk
        run: ./gradlew assembleDebug

      - name: Uploading Test Reports
        if: ${{always()}}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '***/build/reports/tests'

      - name: Uploading APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/**.apk

  code_formatting_job:
    name: Code Formatting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Debug ktlint
        run: ./gradlew ktlintDebugCheck --continue

      - name: Upload ktlint Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ktlint-report
          path: '**/build/reports/ktlint'

      - name: Danger
        if: ${{ always() }}
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_dependeny_updates_job:
    name: Check Dependency Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checking Dependency Versions
        run: ./gradlew dependencyUpdates

      - uses: actions/upload-artifact@v2
        with:
          name: dependencies-report
          path: build/dependencyUpdates/report.txt


  lint_job:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Debug Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: '**/build/reports/lint-results-*'
